### ISSUE TITLE
Compiling in Kodi

### ISSUE THREAD

**Issue by Tony763** [kodi-game/game.libretro.desmume#1]
Hi, I have a problem with compiling. I building all addons at once. Machine is Ubuntu Server 16.10 x86_64
`cd $HOME/src/build-kodi-addons
cmake -DADDONS_TO_BUILD=* \
      -DCMAKE_BUILD_TYPE=Debug \
      -DCMAKE_INSTALL_PREFIX=/home/kodi/src/build-kodi \
      /home/kodi/src/xbmc/project/cmake/addons
make -C $HOME/src/build-kodi-addons/`

` Scanning dependencies of target desmume
make[2]: Opouští se adresář „/home/kodi/src/build-kodi-addons“
make[2]: Vstupuje se do adresáře „/home/kodi/src/build-kodi-addons“
[ 72%] Creating directories for 'desmume'
[ 72%] Performing download step (git clone) for 'desmume'
Cloning into 'desmume'...
Already on 'master'
Your branch is up-to-date with 'origin/master'.
[ 72%] Performing patch step for 'desmume'
[ 72%] Performing update step for 'desmume'
Current branch master is up to date.
Already up-to-date!
[ 73%] Performing configure step for 'desmume'
-- The C compiler identification is GNU 6.2.0
-- The CXX compiler identification is GNU 6.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    BUILD_SHARED_LIBS
    ENABLE_STATIC
    OUTPUT_DIR

-- Build files have been written to: /home/kodi/src/build-kodi-addons/build/desmume/src/desmume-build
[ 73%] Performing build step for 'desmume'
make[3]: Vstupuje se do adresáře „/home/kodi/src/build-kodi-addons/build/desmume/src/desmume-build“
make[4]: Vstupuje se do adresáře „/home/kodi/src/build-kodi-addons/build/desmume/src/desmume-build“
make[5]: Vstupuje se do adresáře „/home/kodi/src/build-kodi-addons/build/desmume/src/desmume-build“
Scanning dependencies of target desmume
make[5]: Opouští se adresář „/home/kodi/src/build-kodi-addons/build/desmume/src/desmume-build“
make[5]: Vstupuje se do adresáře „/home/kodi/src/build-kodi-addons/build/desmume/src/desmume-build“
[ 12%] Creating directories for 'desmume'
[ 25%] No download step for 'desmume'
[ 37%] No patch step for 'desmume'
[ 50%] No update step for 'desmume'
[ 62%] No configure step for 'desmume'
[ 75%] Performing build step for 'desmume'
make[6]: Vstupuje se do adresáře „/home/kodi/src/build-kodi-addons/build/desmume/src/desmume“
In file included from src/armcpu.cpp:30:0:
src/MMU_timing.h: In instantiation of ‘class CacheController<13, 2, 5>’:
src/MMU_timing.h:253:26:   required from here
src/MMU_timing.h:158:28: error: left operand of shift expression ‘(-1 << 11)’ is negative [-fpermissive]
  enum { TAGMASK = (u32)(~0 << TAGSHIFT) };
                        ~~~~^~~~~~~~~~~~
src/MMU_timing.h:158:7: error: enumerator value for ‘TAGMASK’ is not an integer constant
  enum { TAGMASK = (u32)(~0 << TAGSHIFT) };
       ^
src/MMU_timing.h:159:61: error: left operand of shift expression ‘(-1 << 5)’ is negative [-fpermissive]
  enum { BLOCKMASK = ((u32)~0 >> (32 - TAGSHIFT)) & (u32)(~0 << BLOCKSIZESHIFT) };
                            ~~~~^~~~~~~~~~~~~~~~~~
src/MMU_timing.h:159:7: error: enumerator value for ‘BLOCKMASK’ is not an integer constant
  enum { BLOCKMASK = ((u32)~0 >> (32 - TAGSHIFT)) & (u32)(~0 << BLOCKSIZESHIFT) };
       ^
src/MMU_timing.h: In instantiation of ‘class CacheController<12, 2, 5>’:
src/MMU_timing.h:254:26:   required from here
src/MMU_timing.h:158:28: error: left operand of shift expression ‘(-1 << 10)’ is negative [-fpermissive]
  enum { TAGMASK = (u32)(~0 << TAGSHIFT) };
                        ~~~~^~~~~~~~~~~~
src/MMU_timing.h:158:7: error: enumerator value for ‘TAGMASK’ is not an integer constant
  enum { TAGMASK = (u32)(~0 << TAGSHIFT) };
       ^
src/MMU_timing.h:159:61: error: left operand of shift expression ‘(-1 << 5)’ is negative [-fpermissive]
  enum { BLOCKMASK = ((u32)~0 >> (32 - TAGSHIFT)) & (u32)(~0 << BLOCKSIZESHIFT) };
                            ~~~~^~~~~~~~~~~~~~~~~~
src/MMU_timing.h:159:7: error: enumerator value for ‘BLOCKMASK’ is not an integer constant
  enum { BLOCKMASK = ((u32)~0 >> (32 - TAGSHIFT)) & (u32)(~0 << BLOCKSIZESHIFT) };
       ^
<vestavěný>: návod pro cíl „src/armcpu.o“ selhal
make[6]: *** [src/armcpu.o] Chyba 1
make[6]: Opouští se adresář „/home/kodi/src/build-kodi-addons/build/desmume/src/desmume“
CMakeFiles/desmume.dir/build.make:110: návod pro cíl „desmume/src/desmume-stamp/desmume-build“ selhal
make[5]: *** [desmume/src/desmume-stamp/desmume-build] Chyba 2
make[5]: Opouští se adresář „/home/kodi/src/build-kodi-addons/build/desmume/src/   `

**Comment by garbear** [comment]
A quick google suggests that this is because we're trying to compile DeSmuME with c++11/c++14, which I guess it's not compatible with. @fetzerch should we just compile this without c++11?

**Comment by fetzerch** [comment]
We don't pass any additional parameters to the Makefiles. if a core needs C++11/14 it's done in there. Suspicion is that gcc 6.2 is just more picky. We shouldn't really do any compile patches, but just try fixing the upstream libretro makefiles.

Maybe I just picked the wrong repo: there's https://github.com/libretro/desmume which apparently is much more active than https://github.com/libretro/desmume-libretro.

@Tony763: can you support us finding the issue? Please clone https://github.com/libretro/desmume, cd into the directory and run `make -C desmume -f Makefile.libretro` and let me know if that compiles for you.

**Comment by fetzerch** [comment]
The repo we had was definitively the wrong one (compared with what's done in libretro-super). Fixed in https://github.com/kodi-game/game.libretro.desmume/commit/b4f4e23a34835db7946370e81e2e8a804cdd3c93.

Now it's just the question if it works with newer GCCs

**Comment by Tony763** [comment]
>@Tony763: can you support us finding the issue? Please clone https://github.com/libretro/desmume, cd into the directory and run make -C desmume -f Makefile.libretro and let me know if that compiles for you.

Yes, it will successfully compile.

**Comment by fetzerch** [comment]
@Tony763: Thanks. Then you can compile the addons again like you have done in the first post.

**Comment by Tony763** [comment]
Tried and works. Thanks
